<?php

use Drupal\Core\Database\Database;

/**
 * Implements hook_theme().
 */
function calculator_theme($existing, $type, $theme, $path){
	return [
	  'my_template' => [
		'variables' => [
			'nodes' => NULL,
			'total' => 0,
			'adults' => 1,
			'totalPeople' => 1,
			'form' => NULL
		],
	  ],
	  'my_form' => [
		  'variables' => ['form' => NULL]
	  ]
	];
}

/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
//function calculator_page_attachments(array &$page) {
//	$page['#attached']['library'][] = 'calculator/style';
//}